<div style="background: #fff; color: #333333; padding: 30px; position: relative;">
	
<!-- Close button -->
    <div onclick="parent.closePandoraLightbox()" style="background: white; padding: 2px 12px; position: absolute; z-index: 1; right: 0px; top: 0px; cursor: pointer; font-size: 24px; color: #818a91;
    ">×</div>

	<h1>The external page $_GET ID = <span style="color: red;"><?=$_GET['id']?></span></h1>

	<h3>Even with largest content</h3>

	<img src="http://placehold.it/900x300" style="width: 100%;">

	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Provident eaque, eligendi sit tempora vel asperiores ratione esse temporibus deserunt itaque magni vero sequi odit quaerat assumenda vitae iure laudantium sint labore! Minima provident culpa perspiciatis, cupiditate rem, corporis ullam vitae accusamus veniam porro excepturi ut, numquam ea? Assumenda nobis ducimus hic quibusdam repudiandae illum molestias corporis quisquam nam ut iusto aliquam, libero culpa dolores laborum accusantium eveniet laboriosam repellat architecto asperiores, velit consectetur atque adipisci. Optio quasi, minus ipsum repellat nostrum quisquam reiciendis aperiam deleniti. Reiciendis temporibus voluptas saepe consequuntur? Temporibus quis facere similique a porro tempore magnam tenetur qui.</p>

	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Provident eaque, eligendi sit tempora vel asperiores ratione esse temporibus deserunt itaque magni vero sequi odit quaerat assumenda vitae iure laudantium sint labore! Minima provident culpa perspiciatis, cupiditate rem, corporis ullam vitae accusamus veniam porro excepturi ut, numquam ea? Assumenda nobis ducimus hic quibusdam repudiandae illum molestias corporis quisquam nam ut iusto aliquam, libero culpa dolores laborum accusantium eveniet laboriosam repellat architecto asperiores, velit consectetur atque adipisci. Optio quasi, minus ipsum repellat nostrum quisquam reiciendis aperiam deleniti. Reiciendis temporibus voluptas saepe consequuntur? Temporibus quis facere similique a porro tempore magnam tenetur qui.</p>

	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Provident eaque, eligendi sit tempora vel asperiores ratione esse temporibus deserunt itaque magni vero sequi odit quaerat assumenda vitae iure laudantium sint labore! Minima provident culpa perspiciatis, cupiditate rem, corporis ullam vitae accusamus veniam porro excepturi ut, numquam ea? Assumenda nobis ducimus hic quibusdam repudiandae illum molestias corporis quisquam nam ut iusto aliquam, libero culpa dolores laborum accusantium eveniet laboriosam repellat architecto asperiores, velit consectetur atque adipisci. Optio quasi, minus ipsum repellat nostrum quisquam reiciendis aperiam deleniti. Reiciendis temporibus voluptas saepe consequuntur? Temporibus quis facere similique a porro tempore magnam tenetur qui.</p>

	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Provident eaque, eligendi sit tempora vel asperiores ratione esse temporibus deserunt itaque magni vero sequi odit quaerat assumenda vitae iure laudantium sint labore! Minima provident culpa perspiciatis, cupiditate rem, corporis ullam vitae accusamus veniam porro excepturi ut, numquam ea? Assumenda nobis ducimus hic quibusdam repudiandae illum molestias corporis quisquam nam ut iusto aliquam, libero culpa dolores laborum accusantium eveniet laboriosam repellat architecto asperiores, velit consectetur atque adipisci. Optio quasi, minus ipsum repellat nostrum quisquam reiciendis aperiam deleniti. Reiciendis temporibus voluptas saepe consequuntur? Temporibus quis facere similique a porro tempore magnam tenetur qui.</p>

	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Provident eaque, eligendi sit tempora vel asperiores ratione esse temporibus deserunt itaque magni vero sequi odit quaerat assumenda vitae iure laudantium sint labore! Minima provident culpa perspiciatis, cupiditate rem, corporis ullam vitae accusamus veniam porro excepturi ut, numquam ea? Assumenda nobis ducimus hic quibusdam repudiandae illum molestias corporis quisquam nam ut iusto aliquam, libero culpa dolores laborum accusantium eveniet laboriosam repellat architecto asperiores, velit consectetur atque adipisci. Optio quasi, minus ipsum repellat nostrum quisquam reiciendis aperiam deleniti. Reiciendis temporibus voluptas saepe consequuntur? Temporibus quis facere similique a porro tempore magnam tenetur qui.</p>

	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Provident eaque, eligendi sit tempora vel asperiores ratione esse temporibus deserunt itaque magni vero sequi odit quaerat assumenda vitae iure laudantium sint labore! Minima provident culpa perspiciatis, cupiditate rem, corporis ullam vitae accusamus veniam porro excepturi ut, numquam ea? Assumenda nobis ducimus hic quibusdam repudiandae illum molestias corporis quisquam nam ut iusto aliquam, libero culpa dolores laborum accusantium eveniet laboriosam repellat architecto asperiores, velit consectetur atque adipisci. Optio quasi, minus ipsum repellat nostrum quisquam reiciendis aperiam deleniti. Reiciendis temporibus voluptas saepe consequuntur? Temporibus quis facere similique a porro tempore magnam tenetur qui.</p>

	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Provident eaque, eligendi sit tempora vel asperiores ratione esse temporibus deserunt itaque magni vero sequi odit quaerat assumenda vitae iure laudantium sint labore! Minima provident culpa perspiciatis, cupiditate rem, corporis ullam vitae accusamus veniam porro excepturi ut, numquam ea? Assumenda nobis ducimus hic quibusdam repudiandae illum molestias corporis quisquam nam ut iusto aliquam, libero culpa dolores laborum accusantium eveniet laboriosam repellat architecto asperiores, velit consectetur atque adipisci. Optio quasi, minus ipsum repellat nostrum quisquam reiciendis aperiam deleniti. Reiciendis temporibus voluptas saepe consequuntur? Temporibus quis facere similique a porro tempore magnam tenetur qui.</p>

</div>